Clean iptables and disks
Signed-off-by: Shubhranshu Mahapatra <shubhum@amazon.com>

diff --git a/.github/workflows/e2e-ubuntu-finch-daemon.yaml b/.github/workflows/e2e-ubuntu-finch-daemon.yaml
--- a/.github/workflows/e2e-ubuntu-finch-daemon.yaml
+++ b/.github/workflows/e2e-ubuntu-finch-daemon.yaml
@@ -111,14 +111,15 @@ jobs:
           sudo rm -rf /var/lib/soci-snapshotter-grpc/ || true
           sudo rm -rf /var/lib/nerdctl || true
 
+          # Clean up root cache
+          sudo rm -rf /root/.cache || true
+
           # Reload systemd after cleanup
           sudo systemctl daemon-reload
       - name: Check available disk space
         run: |
           sudo df -h
           sudo df -h /tmp
-          sudo du -chx --max-depth=1
-          sudo du -chx --max-depth=1 /tmp
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
         with:
           # We need to get all the git tags to make version injection work. See VERSION in Makefile for more detail.
@@ -134,6 +135,10 @@ jobs:
         run: |
           has_creds=${{ (github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name) && github.actor != 'dependabot[bot]' }}
           echo "has_creds=$has_creds" >> $GITHUB_OUTPUT
+      - name: Clean iptable rules
+        run: |
+          sudo chmod +x ./scripts/clean-iptables.sh
+          sudo ./scripts/clean-iptables.sh
       - name: Install dependencies
         run: |
           sudo apt install build-essential -y
